name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t myapp -f docker_image/dockerfile .

      - name: Run Amenitie App
        run: docker run -d -p 5001:5000 -v myapp_data:/app/data myapp gunicorn -b 0.0.0.0:5000 API.amenitie_app:app

      - name: Run City App
        run: docker run -d -p 5002:5000 -v myapp_data:/app/data myapp gunicorn -b 0.0.0.0:5000 API.city_app:app

      - name: Run Country App
        run: docker run -d -p 5003:5000 -v myapp_data:/app/data myapp gunicorn -b 0.0.0.0:5000 API.country_app:app

      - name: Run Place App
        run: docker run -d -p 5004:5000 -v myapp_data:/app/data myapp gunicorn -b 0.0.0.0:5000 API.place_app:app

      - name: Run Review App
        run: docker run -d -p 5005:5000 -v myapp_data:/app/data myapp gunicorn -b 0.0.0.0:5000 API.review_app:app

      - name: Run User App
        run: docker run -d -p 5006:5000 -v myapp_data:/app/data myapp gunicorn -b 0.0.0.0:5000 API.user_app:app

      - name: Verify Amenitie App
        run: curl -f http://localhost:5001 || exit 1

      - name: Verify City App
        run: curl -f http://localhost:5002 || exit 1

      - name: Verify Country App
        run: curl -f http://localhost:5003 || exit 1

      - name: Verify Place App
        run: curl -f http://localhost:5004 || exit 1

      - name: Verify Review App
        run: curl -f http://localhost:5005 || exit 1

      - name: Verify User App
        run: curl -f http://localhost:5006 || exit 1