FROM python:3.9-alpine

ENV PORT=5000

VOLUME /app/data

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apk update && \
    apk add --no-cache gcc musl-dev linux-headers

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

EXPOSE 5001 5002 5003 5004 5005 5006

# Specify the entry point for the application
CMD ["sh", "-c", "gunicorn -b 0.0.0.0:$PORT API.amenitie_app:app & \
                   gunicorn -b 0.0.0.0:$PORT API.city_app:app & \
                   gunicorn -b 0.0.0.0:$PORT API.country_app:app & \
                   gunicorn -b 0.0.0.0:$PORT API.place_app:app & \
                   gunicorn -b 0.0.0.0:$PORT API.review_app:app & \
                   gunicorn -b 0.0.0.0:$PORT API.user_app:app"]
