FROM python:3.9-alpine

ENV PORT=5000

VOLUME /app/data

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apk update && \
    apk add --no-cache gcc musl-dev linux-headers


WORKDIR /API


COPY docker_image/requirements.txt /API/
RUN pip install --no-cache-dir -r requirements.txt

COPY API/ /API

RUN -t myapp -f dockerfile .

RUN -p 5001:5000 myapp gunicorn -b 0.0.0.0:5000 API.amenitie_app:app

RUN -p 5002:5000 myapp gunicorn -b 0.0.0.0:5000 API.city_app:app

RUN -p 5003:5000 myapp gunicorn -b 0.0.0.0:5000 API.country_app:app

RUN -p 5004:5000 myapp gunicorn -b 0.0.0.0:5000 API.place_app:app

RUN -p 5005:5000 myapp gunicorn -b 0.0.0.0:5000 API.review_app:app

RUN -p 5006:5000 myapp gunicorn -b 0.0.0.0:5000 API.user_app:app